services:
  kwconsultapi:
    image: kwconsultapi
    container_name: kwconsultapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    restart: always
    environment:
      - DEBUG=False